// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfcEwBJIEM2Ng-DQp0HAu02e6Kjkw4cD4',
    appId: '1:1072160951909:web:8c99b2ab8c7054dcf0008c',
    messagingSenderId: '1072160951909',
    projectId: 'flutter-password-manager-25d34',
    authDomain: 'flutter-password-manager-25d34.firebaseapp.com',
    storageBucket: 'flutter-password-manager-25d34.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlcSfq4xwWcCy8w65816SQ4EcWTjx3iLM',
    appId: '1:1072160951909:android:dc21a708c9c33a71f0008c',
    messagingSenderId: '1072160951909',
    projectId: 'flutter-password-manager-25d34',
    storageBucket: 'flutter-password-manager-25d34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHR9d_KcpeJhpv6hrHr-J5Cq0S-e4TjpQ',
    appId: '1:1072160951909:ios:a12d7a402248429df0008c',
    messagingSenderId: '1072160951909',
    projectId: 'flutter-password-manager-25d34',
    storageBucket: 'flutter-password-manager-25d34.appspot.com',
    iosClientId: '1072160951909-etr9bmf0h3fam2mlc0k8d69jl904l9dr.apps.googleusercontent.com',
    iosBundleId: 'se.pixolity.passwordManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHR9d_KcpeJhpv6hrHr-J5Cq0S-e4TjpQ',
    appId: '1:1072160951909:ios:a12d7a402248429df0008c',
    messagingSenderId: '1072160951909',
    projectId: 'flutter-password-manager-25d34',
    storageBucket: 'flutter-password-manager-25d34.appspot.com',
    iosClientId: '1072160951909-etr9bmf0h3fam2mlc0k8d69jl904l9dr.apps.googleusercontent.com',
    iosBundleId: 'se.pixolity.passwordManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfcEwBJIEM2Ng-DQp0HAu02e6Kjkw4cD4',
    appId: '1:1072160951909:web:21218ecbba641208f0008c',
    messagingSenderId: '1072160951909',
    projectId: 'flutter-password-manager-25d34',
    authDomain: 'flutter-password-manager-25d34.firebaseapp.com',
    storageBucket: 'flutter-password-manager-25d34.appspot.com',
  );
}
